services:
  # PostgreSQL Database (optional - for local development)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jewgo
      POSTGRES_USER: jewgo_user
      POSTGRES_PASSWORD: jewgo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - jewgo-network
    restart: unless-stopped

  # Redis for caching (optional - for local development)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - jewgo-network
    restart: unless-stopped

  # Frontend Service (configured to use Render backend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DOCKER=true
      - NEXT_PUBLIC_BACKEND_URL=https://jewgo-app-oyoh.onrender.com
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    env_file:
      - ./frontend/.env.local
    ports:
      - "3001:3000"
    networks:
      - jewgo-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  jewgo-network:
    driver: bridge
