version: '3.8'

services:
  # Redis Master
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    command: redis-server --port 6379 --save 900 1 --save 300 10 --save 60 10000 --dir /data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - redis-cluster
    restart: unless-stopped

  # Redis Slave 1
  redis-slave-1:
    image: redis:7-alpine
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    volumes:
      - redis-slave-1-data:/data
    command: redis-server --port 6379 --slaveof redis-master 6379 --dir /data
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    depends_on:
      - redis-master
    networks:
      - redis-cluster
    restart: unless-stopped

  # Redis Slave 2
  redis-slave-2:
    image: redis:7-alpine
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    volumes:
      - redis-slave-2-data:/data
    command: redis-server --port 6379 --slaveof redis-master 6379 --dir /data
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    depends_on:
      - redis-master
    networks:
      - redis-cluster
    restart: unless-stopped

  # Redis Sentinel 1
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: redis-sentinel --port 26379 --sentinel monitor mymaster redis-master 6379 2 --sentinel auth-pass mymaster your_redis_password_here
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-cluster
    restart: unless-stopped

  # Redis Sentinel 2
  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: redis-sentinel --port 26379 --sentinel monitor mymaster redis-master 6379 2 --sentinel auth-pass mymaster your_redis_password_here
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-cluster
    restart: unless-stopped

  # Redis Sentinel 3
  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: redis-sentinel --port 26379 --sentinel monitor mymaster redis-master 6379 2 --sentinel auth-pass mymaster your_redis_password_here
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-cluster
    restart: unless-stopped

volumes:
  redis-master-data:
  redis-slave-1-data:
  redis-slave-2-data:

networks:
  redis-cluster:
    driver: bridge