services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Point to your real backend URL
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
    volumes:
      # Mount environment files if needed
      - ./config/environment/frontend.env.example:/app/.env.local:ro
    networks:
      - frontend-network
    restart: unless-stopped

networks:
  frontend-network:
    driver: bridge
