services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DOCKER=true
      # Point to your production backend URL
      - NEXT_PUBLIC_API_URL=https://jewgo.onrender.com
      - NEXT_PUBLIC_BACKEND_URL=https://jewgo.onrender.com
      # Supabase Configuration - Update these with your actual values
      - NEXT_PUBLIC_SUPABASE_URL=https://lgsfyrxkqpipaumngvfi.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_0iwWwM0kEGMnDApN5BYfZg_lIXWnD_n
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Google Maps API
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=${NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID}
      # Admin Configuration
      - NEXT_PUBLIC_ADMIN_EMAIL=admin@jewgo.com
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      # Database URL
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend-network
    restart: unless-stopped
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  frontend-network:
    driver: bridge
