[build]
  # Set the directory to the frontend folder where Next.js is located
  base = "frontend"
  
  # Build command for Next.js (work with @netlify/plugin-nextjs)
  command = "npm ci --include=dev && npx prisma generate && npm run build"
  
  # Output directory for the built files
  publish = ".next"

[build.environment]
  # Set Node.js version to match your package.json engines and .nvmrc
  NODE_VERSION = "22"
  
  # Set NPM version for consistency
  NPM_VERSION = "10"
  
  # Build optimization settings
  NODE_OPTIONS = "--max-old-space-size=4096"
  
  # Ensure proper environment
  NODE_ENV = "production"
  
  # Configure secrets scanning to allow NEXT_PUBLIC_ environment variables
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"
  SECRETS_SCAN_OMIT_PATHS = ".next/cache/**,.next/static/**,.next/server/**"

# Environment variables (these will be overridden by Netlify UI or CLI)
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_BACKEND_URL = "https://jewgo.onrender.com"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_BACKEND_URL = "https://jewgo.onrender.com"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_BACKEND_URL = "https://jewgo.onrender.com"

# Functions configuration (if you need serverless functions)
[functions]
  # Directory for Netlify functions (if needed)
  directory = "netlify/functions"

# Redirects and rewrites (these will be handled by _redirects file)
# The _redirects file in your frontend directory will take precedence

# Headers (these will be handled by _headers file)
# The _headers file in your frontend directory will take precedence

# Build settings for optimal performance
[build.processing]
  skip_processing = false

# Asset optimization
[build.processing.images]
  compress = true

# Build optimization
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Build timeout (in seconds)
# Note: Build settings are defined at the top of the file

# Security headers (handled by _headers file)
# Content security policy and other security headers are in _headers

# Edge functions (if needed in the future)
# [[edge_functions]]
#   function = "my-edge-function"
#   path = "/api/edge-function"

# Note: @netlify/plugin-nextjs plugin is active in Netlify UI
# The build configuration is set up to work with the plugin
# Next.js 15 has built-in support for Netlify deployment

# Plugin configuration to work with the active plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
