services:
  # Backend API Service
  - type: web
    name: jewgo-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: https://jewgo.app,https://jewgo-app.vercel.app,https://jewgo.com,https://www.jewgo.com,https://app.jewgo.com
    healthCheckPath: /health
    autoDeploy: true

  # Redis Service
  - type: redis
    name: jewgo-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
