services:
  # Frontend Service
  frontend:
    image: mml555/jewgo-frontend:commit-4391984c
    container_name: jewgo-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - jewgo-network

  # Backend Service
  backend:
    image: mml555/jewgo-backend:commit-886a5ce2
    container_name: jewgo-backend
    ports:
      - "5001:5000"
    env_file:
      - .env.production
    environment:
      - FLASK_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - jewgo-network
    depends_on:
      - redis

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: jewgo-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jewgo-network

networks:
  jewgo-network:
    driver: bridge
