services:
  sandbox:
    build:
      context: ./frontend/sandbox
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/sandbox:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sandbox-network
    restart: unless-stopped

  sandbox-storybook:
    build:
      context: ./frontend/sandbox
      dockerfile: Dockerfile.dev
    ports:
      - "6006:6006"
    volumes:
      - ./frontend/sandbox:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run storybook
    networks:
      - sandbox-network
    restart: unless-stopped

  sandbox-test:
    build:
      context: ./frontend/sandbox
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/sandbox:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm run test
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge
