global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@jewgo.app'
  smtp_auth_username: 'alerts@jewgo.app'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 15m

    # Authentication security alerts
    - match:
        component: authentication
        severity: critical
      receiver: 'security-critical'
      group_wait: 0s
      repeat_interval: 10m

    # Database alerts
    - match:
        component: database
      receiver: 'database-alerts'
      group_wait: 30s
      repeat_interval: 30m

    # Infrastructure alerts
    - match:
        component: infrastructure
      receiver: 'infrastructure-alerts'
      group_wait: 1m
      repeat_interval: 1h

    # Application alerts
    - match:
        component: application
      receiver: 'application-alerts'
      group_wait: 2m
      repeat_interval: 1h

    # Business metrics alerts
    - match:
        component: business
      receiver: 'business-alerts'
      group_wait: 5m
      repeat_interval: 2h

    # Monitoring system alerts
    - match:
        component: monitoring
      receiver: 'monitoring-alerts'
      group_wait: 1m
      repeat_interval: 30m

    # Warning level alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 5m
      repeat_interval: 2h

    # Info level alerts
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 10m
      repeat_interval: 4h

receivers:
  - name: 'default'
    email_configs:
      - to: 'admin@jewgo.app'
        subject: 'JewGo Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@jewgo.app,ops@jewgo.app'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT - IMMEDIATE ATTENTION REQUIRED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#critical-alerts'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          {{ end }}

  - name: 'security-critical'
    email_configs:
      - to: 'security@jewgo.app,admin@jewgo.app'
        subject: '🔒 SECURITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          SECURITY ALERT - IMMEDIATE ATTENTION REQUIRED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#security-alerts'
        title: '🔒 Security Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: 'Security Alert: {{ .GroupLabels.alertname }}'

  - name: 'database-alerts'
    email_configs:
      - to: 'dba@jewgo.app,ops@jewgo.app'
        subject: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
        body: |
          Database Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'infrastructure-alerts'
    email_configs:
      - to: 'ops@jewgo.app'
        subject: '🏗️ Infrastructure Alert: {{ .GroupLabels.alertname }}'
        body: |
          Infrastructure Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'application-alerts'
    email_configs:
      - to: 'dev@jewgo.app,ops@jewgo.app'
        subject: '📱 Application Alert: {{ .GroupLabels.alertname }}'
        body: |
          Application Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'business-alerts'
    email_configs:
      - to: 'business@jewgo.app,admin@jewgo.app'
        subject: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        body: |
          Business Metrics Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'monitoring-alerts'
    email_configs:
      - to: 'ops@jewgo.app'
        subject: '📈 Monitoring Alert: {{ .GroupLabels.alertname }}'
        body: |
          Monitoring System Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'ops@jewgo.app'
        subject: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        body: |
          Warning Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'info-alerts'
    email_configs:
      - to: 'ops@jewgo.app'
        subject: 'ℹ️ Info: {{ .GroupLabels.alertname }}'
        body: |
          Information Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

inhibit_rules:
  # Inhibit warning alerts if critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit individual instance alerts if the service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']

  # Inhibit database alerts if the database is down
  - source_match:
      alertname: 'PostgreSQLDown'
    target_match:
      component: 'database'
    equal: ['instance']

  # Inhibit application alerts if the application is down
  - source_match:
      alertname: 'ApplicationDown'
    target_match:
      component: 'application'
    equal: ['instance']
