route:
  receiver: default
  routes:
    - matchers: [severity="page"]
      receiver: pager
    - matchers: [severity="ticket"]
      receiver: opsroom

receivers:
  - name: default
    email_configs: []
  - name: pager
    pagerduty_configs:
      - routing_key: ${PAGERDUTY_KEY}
  - name: opsroom
    slack_configs:
      - api_url: ${SLACK_WEBHOOK}
        channel: "#ops"