-- Insert sample data for stores and mikvah tables
-- This provides initial data for testing the APIs

-- Insert sample stores data
INSERT INTO stores (
    name, description, address, city, state, zip_code, country,
    latitude, longitude, phone_number, website, email,
    store_type, store_category, business_hours,
    has_parking, has_delivery, has_pickup, accepts_credit_cards, accepts_cash,
    kosher_certification, kosher_category, is_cholov_yisroel, is_pas_yisroel,
    rating, review_count, star_rating, google_rating,
    is_active, is_verified, tags, listing_type
) VALUES 
(
    'Kosher Corner Market',
    'Full-service kosher grocery store with fresh produce, meat, and dairy',
    '123 Main Street',
    'Miami',
    'FL',
    '33101',
    'USA',
    25.7617,
    -80.1918,
    '(305) 555-0123',
    'https://koshercorner.com',
    'info@koshercorner.com',
    'grocery',
    'glatt',
    'Mon-Thu: 8:00 AM - 9:00 PM, Fri: 8:00 AM - 3:00 PM, Sun: 9:00 AM - 8:00 PM',
    true,
    true,
    true,
    true,
    true,
    'OU',
    'glatt',
    true,
    true,
    4.5,
    127,
    4.5,
    4.3,
    true,
    true,
    ARRAY['grocery', 'kosher', 'glatt', 'miami'],
    'store'
),
(
    'Jerusalem Judaica',
    'Complete Judaica store with books, ritual items, and gifts',
    '456 Oak Avenue',
    'Fort Lauderdale',
    'FL',
    '33301',
    'USA',
    26.1224,
    -80.1373,
    '(954) 555-0456',
    'https://jerusalemjudaica.com',
    'orders@jerusalemjudaica.com',
    'judaica',
    'kosher',
    'Mon-Thu: 9:00 AM - 7:00 PM, Fri: 9:00 AM - 2:00 PM, Sun: 10:00 AM - 6:00 PM',
    true,
    false,
    true,
    true,
    true,
    'OU',
    'kosher',
    false,
    false,
    4.8,
    89,
    4.8,
    4.6,
    true,
    true,
    ARRAY['judaica', 'books', 'ritual', 'gifts', 'fort lauderdale'],
    'store'
),
(
    'Chabad Bakery',
    'Fresh kosher bakery with challah, pastries, and bread',
    '789 Pine Street',
    'Boca Raton',
    'FL',
    '33432',
    'USA',
    26.3683,
    -80.1289,
    '(561) 555-0789',
    'https://chabadbakery.com',
    'orders@chabadbakery.com',
    'bakery',
    'pas yisroel',
    'Mon-Thu: 6:00 AM - 8:00 PM, Fri: 6:00 AM - 2:00 PM, Sun: 7:00 AM - 7:00 PM',
    true,
    true,
    true,
    true,
    true,
    'Chabad',
    'pas yisroel',
    true,
    true,
    4.7,
    156,
    4.7,
    4.5,
    true,
    true,
    ARRAY['bakery', 'challah', 'pas yisroel', 'boca raton'],
    'store'
);

-- Insert sample mikvah data
INSERT INTO mikvah (
    name, description, address, city, state, zip_code, country,
    latitude, longitude, phone_number, website, email,
    mikvah_type, mikvah_category, business_hours,
    has_parking, has_disabled_access, has_heating, has_air_conditioning,
    has_private_changing_rooms, has_amenities,
    kosher_certification, kosher_category, is_cholov_yisroel, is_pas_yisroel,
    has_attendant, has_private_sessions, has_group_sessions, has_educational_programs,
    has_fees, fee_amount, fee_currency, accepts_credit_cards, accepts_cash,
    rating, review_count, star_rating, google_rating,
    is_active, is_verified, tags, listing_type
) VALUES 
(
    'Miami Community Mikvah',
    'Beautiful community mikvah with modern facilities and experienced attendants',
    '321 Ocean Drive',
    'Miami Beach',
    'FL',
    '33139',
    'USA',
    25.7907,
    -80.1300,
    '(305) 555-0321',
    'https://miamimikvah.com',
    'info@miamimikvah.com',
    'women',
    'orthodox',
    'Mon-Thu: 6:00 AM - 10:00 PM, Fri: 6:00 AM - 2:00 PM, Sun: 7:00 AM - 9:00 PM',
    true,
    true,
    true,
    true,
    true,
    true,
    'OU',
    'glatt',
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    15.00,
    'USD',
    true,
    true,
    4.9,
    203,
    4.9,
    4.8,
    true,
    true,
    ARRAY['mikvah', 'community', 'miami beach', 'orthodox'],
    'mikvah'
),
(
    'Fort Lauderdale Mikvah',
    'Private mikvah facility with comfortable amenities and professional service',
    '654 Sunrise Boulevard',
    'Fort Lauderdale',
    'FL',
    '33304',
    'USA',
    26.1224,
    -80.1373,
    '(954) 555-0654',
    'https://ftlmikvah.com',
    'appointments@ftlmikvah.com',
    'women',
    'orthodox',
    'Mon-Thu: 7:00 AM - 9:00 PM, Fri: 7:00 AM - 1:00 PM, Sun: 8:00 AM - 8:00 PM',
    true,
    true,
    true,
    true,
    true,
    true,
    'OU',
    'glatt',
    true,
    true,
    true,
    true,
    false,
    false,
    true,
    20.00,
    'USD',
    true,
    true,
    4.6,
    142,
    4.6,
    4.4,
    true,
    true,
    ARRAY['mikvah', 'private', 'fort lauderdale', 'orthodox'],
    'mikvah'
),
(
    'Boca Raton Community Mikvah',
    'Modern mikvah facility serving the Boca Raton Jewish community',
    '987 Palmetto Park Road',
    'Boca Raton',
    'FL',
    '33432',
    'USA',
    26.3683,
    -80.1289,
    '(561) 555-0987',
    'https://bocamikvah.com',
    'info@bocamikvah.com',
    'women',
    'orthodox',
    'Mon-Thu: 6:30 AM - 9:30 PM, Fri: 6:30 AM - 1:30 PM, Sun: 7:30 AM - 8:30 PM',
    true,
    true,
    true,
    true,
    true,
    true,
    'OU',
    'glatt',
    true,
    true,
    true,
    false,
    false,
    true,
    true,
    12.00,
    'USD',
    true,
    true,
    4.7,
    178,
    4.7,
    4.5,
    true,
    true,
    ARRAY['mikvah', 'community', 'boca raton', 'orthodox'],
    'mikvah'
);

-- Verify the data was inserted
SELECT 'Stores inserted:' as info, COUNT(*) as count FROM stores;
SELECT 'Mikvah facilities inserted:' as info, COUNT(*) as count FROM mikvah;
