export { useSearchSuggestions } from './useSearchSuggestions';
export { useRecentSearches } from './useRecentSearches';
export { useSearchInput } from './useSearchInput';
export { useIsMobile } from './useIsMobile';
export { useInfiniteScroll } from './useInfiniteScroll';
export { useScrollDetection } from './useScrollDetection';
export { useCaptcha } from '../../hooks/useCaptcha';
export { usePerformanceMonitor } from './usePerformanceMonitor';
export { useBackgroundPrefetch } from './useBackgroundPrefetch'; 