global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # JewGo Backend API
  - job_name: "jewgo-backend"
    static_configs:
      - targets: ["jewgo-backend-new:5000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Nginx metrics (if nginx-prometheus-exporter is available)
  - job_name: "nginx"
    static_configs:
      - targets: ["jewgo-nginx:9113"]
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is available)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
