# Ruff configuration file
# https://docs.astral.sh/ruff/configuration/

# Target Python version
target-version = "py312"

# Line length
line-length = 88

[lint]
# Enable all rules by default
select = ["ALL"]

# Ignore specific rules
ignore = [
    "E501",  # Line too long (handled by black)
    "E731",  # Do not assign a lambda expression, use a def
    "F401",  # Imported but unused (temporarily ignore)
    "F841",  # Local variable is assigned to but never used (temporarily ignore)
    "PLR0913",  # Too many arguments to function call
    "PLR0915",  # Too many statements
    "PLR0912",  # Too many branches
    "PLR0911",  # Too many return statements
    "PLR2004",  # Magic value used in comparison
    "PLR0916",  # Too many boolean expressions
    "PLR0917",  # Too many positional arguments
]

# Allow autofix for all enabled rules
fixable = ["ALL"]

# Unfixable rules
unfixable = [
    "E501",  # Line too long
    "E731",  # Do not assign a lambda expression, use a def
]

# Exclude files and directories
exclude = [
    ".git",
    ".venv",
    "venv_py311",
    "__pycache__",
    ".pytest_cache",
    "migrations",
    "*.egg-info",
]


