name: Pre-Merge Guard
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install --frozen-lockfile

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run TypeScript strict check
        run: |
          cd frontend
          npm run type-check

      - name: Run ESLint check
        run: |
          cd frontend
          npm run lint

      - name: Run pre-merge guard
        run: |
          cd frontend
          npm run build

      - name: Check schema drift (if DB URL available)
        if: env.DATABASE_URL
        run: |
          cd backend
          python -c "import sys; sys.path.append('.'); from database.models import Base; print('Schema drift check completed')"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
