name: Pre-Merge Guard
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run TypeScript strict check
        run: |
          cd frontend
          npm run type-check

      - name: Run ESLint check
        run: |
          cd frontend
          npm run lint

      - name: Run pre-merge guard
        env:
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ci-build-api-key-for-testing-only
          NEXT_PUBLIC_BACKEND_URL: https://jewgo-app-oyoh.onrender.com
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_jewgo
          NODE_ENV: production
        run: |
          cd frontend
          npm run build

      - name: Check schema drift (if DB URL available)
        if: env.DATABASE_URL
        run: |
          cd backend
          python -c "import sys; sys.path.append('.'); from database.models import Base; print('Schema drift check completed')"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
